// react/src/components/TodoItem/TodoItem.tsx
import React, {FC, MouseEvent, useContext} from 'react';
import { TodosContext } from '../../App';
import type { ITodo } from '../../types';

export const TodoItem: FC<ITodo & {index: number}> = function(props) {
  const { dispatch } = useContext(TodosContext);
  function handleDelete(e: MouseEvent) {
    dispatch({
      type: 'delete',
      payload: {
        index: props.index
      }
    })
  }

  return (
    <li>
      {props.title}
      <button type="button" onClick={handleDelete}>&times;</button>
    </li>
  )
}

// svelte/src/components/TodoItem/TodoItem.svelte
<script lang="ts">
  import type { ITodo } from '../../types';
  import { store } from '../../App.svelte';

  export let title: ITodo['title'];
  export let index: number;

  function handleDelete(e: MouseEvent) {
    store.update((state) => {
      const newTodos = [...state.todos];
      newTodos.splice(index, 1);
      return {
        ...state,
        todos: newTodos
      }
    });
  }
</script>

<li>
  {title}
  <button on:click={handleDelete}>&times;</button>
</li>

<style>
  li {
    border-bottom: 1px solid #ccc;
  }
</style>
