// svelte/src/components/AddTodo/AddTodo.svelte
<script lang="ts">
  import { store } from '../../App.svelte';
  
  let title: string = '';

  function handleSubmit() {
    store.update((state) => {
      return {
        ...state,
        todos: [
          ...state.todos,
          {
            title
          }
        ]
      }
    });
  }
</script>

<form on:submit|preventDefault={handleSubmit}>
  <input bind:value={title}>
  <button type="submit">Add todo</button>
</form>

// react/src/components/AddTodo/AddTodo.tsx
import React, { FC, FormEvent, useContext, useState } from 'react';
import { TodosContext } from '../../App';

export const AddTodo: FC = function() {
  const {dispatch} = useContext(TodosContext);
  const [title, setTitle] = useState<string>('');

  function handleSubmit(e: FormEvent) {
    e.preventDefault();

    dispatch({
      type: 'add',
      payload: {
        todo: {
          title
        }
      }
    })
  }

  return (
    <form onSubmit={handleSubmit}>
      <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} />
      <button type="submit">Add todo</button>
    </form>
  )
}
